### ISSUE TITLE
JSX files

### ISSUE THREAD

**Issue by mysiar** [jpsierens/webpack-react-redux-react-router#18]
not really the issue but I would like to use JSX files instead JS,
could you help me out to change webpack.config.js file ?

**Comment by marudhupandiyang** [comment]
I think this is more of an `stackoverflow` question than to be here. Please try the below

1. Rename all(or only the ones that you require) `js` files to `jsx` except these `server.js`, `webpack.config.js`, `webpack.production.config.js`.
2. In `webpack.config.js` change `.js` to `.jsx` under `entry` and `module`.
3. Add the below to `webpack.config.js`under `module.exports`, so that webpack starts resolving `jsx` files too

      resolve: {
                      extensions: ['', '.js', '.jsx']
     },

And you should be done. Hope that helps.

**Comment by mysiar** [comment]
Thanks, that helped
