### ISSUE TITLE
Open dist/index.html in browser, I got a blank page.

### ISSUE THREAD

**Issue by nxf** [jpsierens/webpack-react-redux-react-router#35]
I cloned the project from master, When npm start, I can see the page. But when I execute the command, npm run build, It produce the dist/index.html and css/jss. But When I access the index.html from browser, I can not see anything. It's blank.

**Comment by helb** [comment]
That's because the build output is meant to be served by a webserver, not just opened from disk. If you open the browser console (F12), you'd see something like this:

![kookaburra_20180305_105332](https://user-images.githubusercontent.com/178133/36968678-8daf4902-2063-11e8-98a2-af0f3876e733.png)

That means the browser is trying to find `main-xxx.min.js` and `main-xxx.min.css` in the website root, which, when you open the file that way, is… none.

There are some easy to use webservers with no configuration needed, for example :

```
$ npm install -g http-server
$ cd dist
$ hs -o    # -o opens the browser automatically
Starting up http-server, serving ./
Available on:
  http://127.0.0.1:8080
Hit CTRL-C to stop the server
```
